name: bluesmallpig-scripts
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest    
    steps:
      - name: Step1
        run:
          echo "${{ github.repository }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event.repository.owner.id }}"
          echo "${{ github.event.sender.id }}"
          
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync bluesmallpig-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/bluesmallpig/scripts.git"
          source_branch: "main"
          destination_branch: "bluesmallpig"
          github_token: ${{ secrets.PAT }}
