name: LinYuanovo-scripts
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-LinYuanovo-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync LinYuanovo-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/LinYuanovo/scripts.git"
          source_branch: "main"
          destination_branch: "LinYuanovo"
          github_token: ${{ secrets.PAT }}
