name: pojiezhiyuanjun-sync
on:
  schedule:
    - cron: '15 6,12,14,16,18 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-pojiezhiyuanjun-freev2
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync pojiezhiyuanjun-freev2
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/pojiezhiyuanjun/freev2.git"
          source_branch: "master"
          destination_branch: "pojiezhiyuanjun"
          github_token: ${{ secrets.PAT }}
          
