name: sngxpro-sync
on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-sngxpro-QuanX
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync sngxpro-QuanX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sngxpro/QuanX.git"
          source_branch: "master"
          destination_branch: "sngxpro"
          github_token: ${{ secrets.PAT }}   
