name: _test
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    steps:
      - name: Step1
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.event_name }}"
