name: _test
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event.repository.owner.id }}"
          echo "${{ github.event.sender.id }}"

