name: kxs2018-xiaoym-sync
on:
  schedule:
    - cron: '25 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-kxs2018-xiaoym
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync kxs2018-xiaoym
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/kxs2018/xiaoym.git"
          source_branch: "main"
          destination_branch: "kxs2018"
          github_token: ${{ secrets.PAT }}
