name: xl2101200-sync
on:
  schedule:
    - cron: '25 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-xl2101200--
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync xl2101200--
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xl2101200/-.git"
          source_branch: "main"
          destination_branch: "xl2101200"
          github_token: ${{ secrets.PAT }}
