https://github.com/xzxxn777/Surge?tab=readme-ov-file
name: xzxxn777-Surge
on:
  schedule:
    - cron: '15 6,12,14,16,18 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-xzxxn777-Surge
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync xzxxn777-Surge
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xzxxn777/Surge.git"
          source_branch: "main"
          destination_branch: "xzxxn777"
          github_token: ${{ secrets.PAT }}
          
