name: YaphetS0903-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-YaphetS0903-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync YaphetS0903-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/YaphetS0903/JStest.git"
          source_branch: "main"
          destination_branch: "YaphetS0903"
          github_token: ${{ secrets.PAT }}
